apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-scraper-config
data:
  SCALE_MAC: ""
  AGE: ""
  HEIGHT_CM: ""
  GENDER: ""
  
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "scaledb"
  DB_USER: "scaleuser"